{
 "title": "Monitoramento Modelo",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Monitoramento de Data Drift",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "feature_input_iaa", "legendFormat": "IAA Recebido" },
    { "expr": "feature_input_ieg", "legendFormat": "IEG Recebido" }
   ]
  },
  {
   "title": "Volume de Predições (Risco vs Sem Risco)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "modelo_predicoes_total", "legendFormat": "Risco: {{risco_detectado}}" }
   ]
  },
  {
   "title": "Probabilidade Média de Risco (Últimos 5 min)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(modelo_probabilidade_risco_sum[5m]) / rate(modelo_probabilidade_risco_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Terminal de Logs da API (Tempo Real)",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "{job=\"fastapi_logs\"}"
    }
   ]
  }
 ]
}